//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;
using DotNetNuke.UI.UserControls;
using DotNetNuke.UI.WebControls;

namespace ObserverOfScience
{
	public partial class EditObserverOfScience
	{	
		protected RequiredFieldValidator valContent;
		protected LinkButton cmdUpdate;
		protected LinkButton cmdCancel;
		protected LinkButton cmdDelete;
		protected ModuleAuditControl ctlAudit;

		protected LabelControl lblTitle;
		protected TextBox  txtTitle;
		protected LabelControl lblStatus;
		protected TextBox txtStatus;
		protected LabelControl lblYearOfCreation;
		protected TextBox txtYearOfCreation;
		protected LabelControl lblDescription;
		protected TextEditor txtDescription;
		protected LabelControl lblInventionEssence;
		protected TextEditor txtInventionEssence;
		protected LabelControl lblAdvantages;
		protected TextEditor txtAdvantages;




				

	}
}

